CREATE TABLE client_auth (id SERIAL PRIMARY KEY, username VARCHAR(25) NOT NULL UNIQUE,
password VARCHAR(100) NOT NULL, email VARCHAR(100) UNIQUE, phone_number VARCHAR(20) UNIQUE,
role VARCHAR(20) NOT NULL);